name: Deploy Demo
on: 
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Deploy
        run: |
          chmod 777 startup.sh
          apt-get install dos2unix
          dos2unix startup.sh 
          sh startup.sh 
