name: Deploy Demo
on: 
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Deploy
        run: |
          source /etc/profile
          sh startup.sh 
