name: Deploy Demo
on: 
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Deploy
        run:
          sudo chmod 777 startup.sh
          sudo apt-get install dos2unix
          sudo dos2unix startup.sh 
          sudo sh startup.sh 
