name: Deploy Demo
on: 
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Deploy
        env:
          branch: one
          folder: after
          build_script: sh startup.sh 
